baseURL = 'https://sungjin.dev/'
defaultContentLanguage = "en"
languageCode = "en"
title = "SungJin"

theme = "gokarna"

pygmentsStyle = "monokai"
enableRobotsTXT = true
enableEmoji = true

[params]
  footer = "SungJin Um"
  description = "A singular researcher, charting paths others cannot tread."
  avatarURL = "https://avatars.githubusercontent.com/u/82138254?v=4"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/sungjin-um/"},
    {name = "instagram", url = "https://www.instagram.com/0x0515a/"},
    {name = "email", url = "mailto:me@sungjin.dev"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Publications"
    pre = "<span data-feather='book'></span>"
    url = "/pubs/"
    weight = 1
    
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    pre = "<span data-feather='file-text'></span>"
    post = ""
    name = "Posts"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/taintlesscupcake"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
